### ISSUE TITLE
minio-hs-0.3.2 build fails with latest resourcet

### ISSUE THREAD

**Issue by DanBurton** [minio/minio-hs#79]
As seen on the Stackage build server:

```
[ 6 of 16] Compiling Network.Minio.Data ( src/Network/Minio/Data.hs, dist/build/Network/Minio/Data.o )

src/Network/Minio/Data.hs:437:7: error:
    • No instance for (MonadBase IO (ResourceT IO))
        arising from the 'deriving' clause of a data type declaration
      Possible fix:
        use a standalone 'deriving instance' declaration,
          so you can specify the instance context yourself
    • When deriving the instance for (MonadBase IO Minio)
    |
437 |     , MonadBase IO
    |       ^^^^^^^^^^^^
```

I was able to reproduce the failure locally like so:

```bash
stack unpack minio-hs-0.3.2 && cd minio-hs-0.3.2
edit stack.yaml # add the following stack.yaml
stack build
```

```yaml
# stack.yaml
resolver: nightly-2018-03-10
extra-deps:
- resourcet-1.2.0
- conduit-1.3.0
- conduit-extra-1.3.0
- http-conduit-2.3.0
- xml-conduit-1.8.0
- conduit-combinators-1.3.0
```
